// Service catalog. Each entry = left-sidebar tab + webview target.

export const SERVICES = [
  {
    id: 'telegram',
    name: 'Telegram',
    url: 'https://web.telegram.org/a/',
    partition: 'persist:telegram',
    accent: '#229ED9',
    gradient: 'linear-gradient(135deg, #2AABEE 0%, #229ED9 100%)',
    icon: 'telegram',
  },
  {
    id: 'discord',
    name: 'Discord',
    url: 'https://discord.com/app',
    partition: 'persist:discord',
    accent: '#5865F2',
    gradient: 'linear-gradient(135deg, #7289DA 0%, #5865F2 100%)',
    icon: 'discord',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    url: 'https://www.youtube.com/',
    partition: 'persist:youtube',
    accent: '#FF0033',
    gradient: 'linear-gradient(135deg, #ff4b5c 0%, #ff0033 100%)',
    icon: 'youtube',
    tabbed: true,
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    url: 'https://www.tiktok.com/',
    partition: 'persist:tiktok',
    accent: '#FF0050',
    gradient: 'linear-gradient(135deg, #25F4EE 0%, #FF0050 100%)',
    icon: 'tiktok',
  },
  {
    id: 'steam',
    name: 'Steam',
    url: 'https://store.steampowered.com/',
    partition: 'persist:steam',
    accent: '#66C0F4',
    gradient: 'linear-gradient(135deg, #1B2838 0%, #66C0F4 100%)',
    icon: 'steam',
    tabbed: true,
  },
  {
    id: 'google',
    name: 'Google',
    url: 'https://www.google.com/',
    partition: 'persist:google',
    accent: '#4285F4',
    gradient: 'linear-gradient(135deg, #EA4335 0%, #FBBC05 35%, #34A853 65%, #4285F4 100%)',
    icon: 'google',
    tabbed: true,
  },
  {
    id: 'gmail',
    name: 'Gmail',
    url: 'https://mail.google.com/mail/u/0/',
    partition: 'persist:gmail',
    accent: '#EA4335',
    gradient: 'linear-gradient(135deg, #4285F4 0%, #EA4335 100%)',
    icon: 'gmail',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    url: 'https://www.twitch.tv/',
    partition: 'persist:twitch',
    accent: '#9146FF',
    gradient: 'linear-gradient(135deg, #9146FF 0%, #6441A5 100%)',
    icon: 'twitch',
  },
];
